[ENH] Update GitHub Actions workflow to include Clang and cpplint checks - Add logging for reports

diff --git a/.github/workflows/pain_au_chocolat.yaml b/.github/workflows/pain_au_chocolat.yaml
--- a/.github/workflows/pain_au_chocolat.yaml
+++ b/.github/workflows/pain_au_chocolat.yaml
@@ -45,7 +45,7 @@ jobs:
           fi
 
   build:
-    name: Build project
+    name: Build project & Check Clang & cpplint style
     runs-on: ubuntu-latest
     needs: [cancel-if-mirror]
     if: needs.cancel-if-mirror.outputs.should_cancel == 'false'
@@ -81,19 +81,66 @@ jobs:
           cd build
           cmake --build . --target clang-check || true
 
-      - name: Create annotations for clang-check errors
+      - name: Create annotations for clang-check
         if: steps.clang-check.outcome == 'failure'
         run: |
-          clang_check_log="clang-check.log"
+          clang_check_log="../Logs/clang-reports.log"
+          error_found=false
+          if [ -f $clang_check_log ]; then
+            while IFS= read -r line; do
+              if echo "$line" | grep -q "error:"; then
+                file=$(echo "$line" | awk -F':' '{print $1}')
+                line_num=$(echo "$line" | awk -F':' '{print $2}')
+                msg=$(echo "$line" | cut -d':' -f4- | sed 's/^[[:space:]]*//')
+                echo "::error file=$file,line=$line_num::$msg"
+                error_found=true
+              elif echo "$line" | grep -q "warning:"; then
+                file=$(echo "$line" | awk -F':' '{print $1}')
+                line_num=$(echo "$line" | awk -F':' '{print $2}')
+                msg=$(echo "$line" | cut -d':' -f4- | sed 's/^[[:space:]]*//')
+                echo "::warning file=$file,line=$line_num::$msg"
+              elif echo "$line" | grep -q "note:"; then
+                file=$(echo "$line" | awk -F':' '{print $1}')
+                line_num=$(echo "$line" | awk -F':' '{print $2}')
+                msg=$(echo "$line" | cut -d':' -f4- | sed 's/^[[:space:]]*//')
+                echo "::notice file=$file,line=$line_num::$msg"
+              fi
+            done < $clang_check_log
+          fi
+          if [ "$error_found" = true ]; then
+            exit 1
+          fi
+
+      - name: Run cpplint-check
+        id: cpplint-check
+        run: |
           cd build
-          cmake --build . --target clang-check 2> $clang_check_log || true
-          while IFS= read -r line; do
-            file=$(echo "$line" | awk -F':' '{print $1}')
-            line_num=$(echo "$line" | awk -F':' '{print $2}')
-            msg=$(echo "$line" | cut -d':' -f3-)
-            echo "::error file=$file,line=$line_num::$msg"
-          done < $clang_check_log
-          exit 1
+          cmake --build . --target cpplint-check || true
+
+      - name: Create annotations for cpplint-check
+        if: steps.cpplint-check.outcome == 'failure'
+        run: |
+          cpplint_log="../Logs/cpplint-reports.log"
+          error_found=false
+          if [ -f $cpplint_log ]; then
+            while IFS= read -r line; do
+              severity=$(echo "$line" | awk -F'[][]' '{print $2}')
+              file=$(echo "$line" | awk -F':' '{print $1}')
+              line_num=$(echo "$line" | awk -F':' '{print $2}')
+              msg=$(echo "$line" | cut -d':' -f3- | sed 's/^[[:space:]]*//')
+              if [ "$severity" -ge 4 ]; then
+                echo "::error file=$file,line=$line_num::$msg"
+                error_found=true
+              elif [ "$severity" -ge 2 ]; then
+                echo "::warning file=$file,line=$line_num::$msg"
+              elif [ "$severity" -ge 0 ]; then
+                echo "::notice file=$file,line=$line_num::$msg"
+              fi
+            done < $cpplint_log
+          fi
+          if [ "$error_found" = true ]; then
+            exit 1
+          fi
 
       - name: Check binary
         run: |
@@ -154,6 +201,7 @@ jobs:
           if [ $NB_ERROR -gt 0 ]; then
             exit 1
           fi
+
 
   push_to_mirror:
     name: Pushing to good repository
